apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-worker
  minReplicas: {{ .Values.TRUNKPLAYER_NG_WORKER_REPLICAS_MIN }}
  maxReplicas: {{ .Values.TRUNKPLAYER_NG_WORKER_REPLICAS_MAX }}
  targetCPUUtilizationPercentage: 50