apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-worker
  name: {{ .Release.Name }}-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.TRUNKPLAYER_NG_WORKER_REPLICAS_MIN }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      containers:
        - image: trunkplayer/trunkplayer-ng:{{ .Chart.AppVersion }}
          name: {{ .Release.Name }}-worker
          command: 
            - celery 
            - "-A"
            - trunkplayerNG
            - worker
            - "-l"
            - info
            - "--pool=gevent"
            - "--concurrency=100"
            - "-Q"
            - "default,transmission_forwarding,RR_IMPORT,radio_alerts,radio_tx"
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          resources: 
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 56Mi
              cpu: "100m"
                  {{ if not .Values.USE_S3 }}
          volumeMounts:
            - mountPath: /code/static
              name: {{ .Release.Name }}-staticfiles
            - mountPath: /code/mediafiles
              name: {{ .Release.Name }}-mediafiles
      volumes:
        - name: {{ .Release.Name }}-staticfiles
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-staticfiles
        - name: {{ .Release.Name }}-mediafiles
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mediafiles
        {{ end }}
      restartPolicy: Always
