apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
      app: {{ .Release.Name }}-web
spec:
  ports:
    - name: "nginx-api"
      port: 80
      targetPort: 80
  selector:
      app: {{ .Release.Name }}-web